#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          resizebtrfs_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

function start (){
case "$1" in
  start)
    echo "Starting resizebtrfs_once" | tee /var/log/resizebtrfs_once.log
    ROOT_DEV=$(findmnt / -o source -n | sed 's/\[.*//')
    parted $ROOT_DEV resizepart 3 yes 100% | tee -a /var/log/resizebtrfs_once.log
    btrfs filesystem resize max / | tee -a /var/log/resizebtrfs_once.log
#    resize2fs $ROOT_DEV &&
    update-rc.d resizebtrfs_once remove
#    rm /etc/init.d/resizebtrfs_once
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
}
start start
